AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'db/**/*.rb'
    - 'doc/**/*.xml'
    - '.pryrc'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'Gemfile'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - Gemfile

Metrics/MethodLength:
  Max: 20
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal